(function(g){var window=this;var k4=function(a,b,c){var d=b.sa();g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.rB&&b.lengthSeconds?g.eR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.mE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.rB?b.va:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.jj||g.KN("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",
{TITLE:b.title}),duration:f,url:b.Uh(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.oE&&(d.playlist_length=b.getLength());a.update(d)},l4=function(a,b){g.lD.call(this,{B:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},m4=function(a){g.W.call(this,{B:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",V:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{B:"span",G:"ytp-upnext-title",V:"{{title}}"},{B:"span",G:"ytp-upnext-author",V:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",
J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",V:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
V:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.B(this,this.A);this.A.da("click",this.qI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.J(this.Wl,5E3,this);g.B(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.dK);this.Iy();this.K(a,"autonavvisibility",this.Iy);this.K(a,"mdxnowautoplaying",this.vJ);this.K(a,"mdxautoplaycanceled",this.wJ);this.K(a,"mdxautoplayupnext",this.fB);3==this.l.getPresentingPlayerType()&&
(a=(a=g.BK(g.vK(this.l)))?a.lD():null)&&this.fB(a)},n4=function(a,b){if(!a.o){g.jq("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+a.u.title);
a.H=g.M();a.o=new g.J((0,g.x)(a.ep,a,b),25);a.ep(b);var c=b||g.P(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.lo(a.element,"ytp-upnext-autoplay-paused")},p4=function(a){o4(a);
a.H=g.M();a.ep();g.H(a.element,"ytp-upnext-autoplay-paused")},o4=function(a){a.o&&(a.o.dispose(),a.o=null)},q4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.sa(),a.Wl(),a.C=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:c.title,icon:c.yc()}),a.D=a.K(a.C,"click",a.VJ),a.F.start())}o4(a);a.l.nextVideo(!1,b)},r4=function(a){l4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Sd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",V:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.B(this,this.l);this.l.g(this.element);this.o=new g.qW("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",null,!0,!1,b.Sf,b.subscribed,
"trailer-endscreen",null,null,a);g.B(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},s4=function(a){var b=g.X(a),c=g.jx||g.Dh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",W:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",V:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",V:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{B:"span",G:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{B:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",V:"{{playlist_length}}"},")"]}]},{B:"span",W:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{B:"span",G:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ps(this);g.B(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.yO(a.app.T,this.element,this);this.C()},t4=function(a){g.RK(a.l,a.element);
var b=a.o.sa().videoId,c=a.o.getPlaylistId();g.wY(a.l.app,b,a.o.Ub,c,void 0,void 0)},u4=function(a){l4.call(this,a,"videowall-endscreen");
this.F=a;this.A=0;this.o=[];this.C=this.O=this.u=null;this.D=this.P=!1;this.M=null;this.ca=new g.Ps(this);g.B(this,this.ca);this.H=new g.J(g.Qa(g.H,this.element,"ytp-show-tiles"),0);g.B(this,this.H);var b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},J:[g.NP()]});g.B(this,b);b.g(this.element);b.da("click",this.HF,this);this.I=new g.gD({B:"div",G:"ytp-endscreen-content"});g.B(this,this.I);this.I.g(this.element);b=new g.W({B:"button",
W:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},J:[g.OP()]});g.B(this,b);b.g(this.element);b.da("click",this.GF,this);this.l=new m4(a);g.B(this,this.l);g.OK(this.player,this.l.element,4);this.hide()},v4=function(a){return g.PK(a.player)&&a.zu()&&!a.C},w4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.tS(g.X(a.F),c);
g.B(a,c);return c})},x4=function(a){var b=a.Pe();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},z4=function(a){g.bL.call(this,a);
this.g=null;this.i=new g.Ps(this);g.B(this,this.i);this.l=g.X(a);y4(a)?this.g=new u4(this.player):this.l.Ja?this.g=new r4(this.player):this.g=new l4(this.player);g.B(this,this.g);g.OK(this.player,this.g.element,4);this.bA();this.i.K(a,"videodatachange",this.bA,this);this.i.K(a,g.lE("endscreen"),this.VE,this);this.i.K(a,"crx_endscreen",this.WE,this)},y4=function(a){a=g.X(a);
return a.Fa&&!a.Ja};
g.t(l4,g.lD);l4.prototype.create=function(){this.created=!0};
l4.prototype.destroy=function(){this.created=!1};
l4.prototype.zu=function(){return!1};
l4.prototype.Pe=function(){return!1};g.t(m4,g.W);g.h=m4.prototype;g.h.Wl=function(){this.C&&(this.F.stop(),this.Ma(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.Iy=function(){g.kD(this,this.l.Pe())};
g.h.VJ=function(){window.focus();this.Wl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.ep=function(a){a=a||g.P(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.M()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?q4(this,!0):this.o&&this.o.start()};
g.h.dK=function(a){!g.$d(this.A.element,g.hs(a))&&g.wS(a,this.l)&&q4(this)};
g.h.qI=function(){g.xK(this.l,!0)};
g.h.vJ=function(a){this.l.getPresentingPlayerType();this.show();n4(this,a)};
g.h.fB=function(a){this.l.getPresentingPlayerType();this.u&&this.u.sa().videoId==a.sa().videoId||(this.u=a,k4(this,a,"hqdefault.jpg"))};
g.h.wJ=function(){this.l.getPresentingPlayerType();o4(this);this.hide()};
g.h.U=function(){o4(this);this.Wl();g.W.prototype.U.call(this)};g.t(r4,l4);g.t(s4,g.W);s4.prototype.D=function(a){g.wS(a,this.l,this.A,this.o.Ub||void 0)&&t4(this)};
s4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.ms(a)||(t4(this),g.ls(a))}};
s4.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Pb?!1:b.i};g.t(u4,l4);g.h=u4.prototype;g.h.create=function(){l4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=w4(this,a),this.O=a);this.Lf();this.ca.K(this.player,"appresize",this.Lf);this.ca.K(this.player,"onVideoAreaChange",this.Lf);this.ca.K(this.player,"videodatachange",this.IF);this.ca.K(this.player,"autonavchange",this.qr);this.ca.K(this.player,"autonavcancel",this.FF);a=this.O.autonavState;a!=this.M&&this.qr(a);this.ca.K(this.element,"transitionend",this.sL)};
g.h.destroy=function(){g.Rs(this.ca);g.sf(this.o);this.o=[];this.u=null;l4.prototype.destroy.call(this);g.lo(this.element,"ytp-show-tiles");this.H.stop();this.M=this.O.autonavState};
g.h.zu=function(){return 1!=this.O.autonavState};
g.h.show=function(){l4.prototype.show.call(this);g.lo(this.element,"ytp-show-tiles");g.X(this.player).g?g.zo(this.H):this.H.start();(this.D||this.C&&this.C!=this.O.clientPlaybackNonce)&&g.xK(this.player,!1);v4(this)?(x4(this),2==this.O.autonavState?g.O(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?q4(this.l,!0):n4(this.l):3==this.O.autonavState&&p4(this.l)):(g.xK(this.player,!0),x4(this))};
g.h.hide=function(){l4.prototype.hide.call(this);p4(this.l);x4(this)};
g.h.sL=function(a){g.hs(a)==this.element&&this.Lf()};
g.h.Lf=function(){if(this.u&&this.u.length){g.H(this.element,"ytp-endscreen-paginate");var a=g.FK(this.F,!0),b=g.AD(this.F);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.pd(a.width/m||1,1,1.21);n*=g.pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.Sh(a,m,n);g.Ah(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;k4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",v4(this));x4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.qd(q+this.A,l),0!=r){u=this.o[c];u||(u=new s4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-C-4;g.Ih(u.element,C,z);g.Sh(u.element,E,F);g.Ah(u.element,"transitionDelay",(k+f)/20+"s");g.I(u.element,"ytp-videowall-still-mini",1==r);g.I(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.u[q];r.o!=q&&(r.o=q,k4(r,q,g.jo(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),q=(q=q.Ub)&&q.itct)&&(u=r.l,g.X(u).F&&g.zO(u.app.T,r.element,q));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.rf(e);this.o.length=c}};
g.h.IF=function(){var a=this.player.getVideoData();this.O!=a&&(this.A=0,this.u=w4(this,a),this.O=a,this.Lf())};
g.h.GF=function(){this.A+=this.o.length;this.Lf()};
g.h.HF=function(){this.A-=this.o.length;this.Lf()};
g.h.kE=function(){return!!this.l.o};
g.h.qr=function(a){1==a?(this.D=!1,this.C=this.O.clientPlaybackNonce,o4(this.l),this.Ga()&&this.Lf()):(this.D=!0,this.Ga()&&v4(this)&&(2==a?n4(this.l):3==a&&p4(this.l)))};
g.h.FF=function(a){if(a){for(a=0;a<this.o.length;a++)g.SK(this.F,this.o[a].element,!0);this.qr(1)}else this.C=null,this.D=!1;this.Lf()};
g.h.Pe=function(){return this.Ga()&&v4(this)};g.t(z4,g.bL);g.h=z4.prototype;g.h.Uk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!y4(this.player)||b;a=a.Nc||g.bz(a.Na);var c=g.XX(this.player.app);return b&&!a&&!c};
g.h.Pe=function(){return this.g.Pe()};
g.h.fE=function(){return this.Pe()?this.g.kE():!1};
g.h.U=function(){g.KK(this.player,"endscreen");g.bL.prototype.U.call(this)};
g.h.load=function(){g.bL.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.bL.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.VE=function(a){this.Uk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.WE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.bA=function(){g.KK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.iE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.B(this,a);var b=new g.iE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.B(this,b);g.HK(this.player,[a,b])};g.xV.endscreen=z4;})(_yt_player);
